name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production       # can require manual approval in GitHub UI
    steps:
      - name: Deploy to production
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
          ENV_VAR: ${{ vars.ENV_VAR }}
          REPO_SECRET: ${{ secrets.REPO_SECRET }}
          REPO_VAR: ${{ vars.REPO_VAR }}
        run: |
          echo "Deploying to production environment"
          echo "$ENV_SECRET"
          echo "$ENV_VAR"
          echo "$REPO_VAR"
          echo "$REPO_SECRET"
      - name: GITHUB SECRET AUTO MASK - Will show *** in logs
        run: echo "${{ secrets.ENV_SECRET }}"